//ECO030 - TP3
//Andre Viana 25037

//O PROGRAMA INSTANCIA A INTERFACE E ELA SE ENCARREGA DE GERENCIAR OS METODOS,
//INCLUINDO O ALMOXARIFADO.
//CONSTRUTORES NAO LANCAM EXCECOES POR QUE TRABALHAR DIRETAMENTE NA ENTRADA
//DOS DADOS É UMA SOLUCAO MAIS EFICIENTE.
//A FALTA DE OPERATOR OVERLOADING NA LINGUAGEM FEZ O CÓDIGO DAS OPERACOES
//BASTANTE DIFICIL DE SER LIDO, ISSO ATRAPALHOU MUITO O PROCESSO DE DEBUGGING.

public class base
{
	public static void main (String args[])
	{
		_Interface console = new _Interface();
		System.out.print("\n");
		console.menu();
	}
}
